"""create tables for hotel, room, etc

Revision ID: ef9f498b760e
Revises: b1e72242840c
Create Date: 2023-05-23 15:39:32.489558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9f498b760e'
down_revision = 'b1e72242840c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('parse_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('hotel_id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('link'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('parse_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], ),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('hotel_id', 'room_type', 'name')
    )
    op.create_table('search_points',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('distance_type', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('search_id')
    )
    op.create_table('hotels_to_search',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('searchpoint_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], ),
    sa.ForeignKeyConstraint(['searchpoint_id'], ['search_points.search_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('rooms_cnt_per_day',
    sa.Column('roomcnt_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('cnt', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('roomcnt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms_cnt_per_day')
    op.drop_table('hotels_to_search')
    op.drop_table('search_points')
    op.drop_table('rooms')
    op.drop_table('hotels')
    # ### end Alembic commands ###
