"""test running migrations

Revision ID: 07effe7b9d7b
Revises: 25a0c8b2ecf1
Create Date: 2023-05-14 18:23:45.342266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07effe7b9d7b'
down_revision = '25a0c8b2ecf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
