"""test running migrations

Revision ID: 2b108c7cf28f
Revises: c1b81f125471
Create Date: 2023-05-14 18:15:10.957730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b108c7cf28f'
down_revision = 'c1b81f125471'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
